name: Update Geo List

on:
  push:
    branches: [master, main]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Update Geo List
        run: python3 list.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git commit -am "Update geolist.txt"
          git commit -am "Update !cn.txt"
          git commit -am "Update -cn.txt"
          git commit -am "Update @cn.txt"
          git commit -am "Update ads.txt"
          git commit -am "Update category.txt"
          git push
