name: Update Geo List

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Update Geo List
        run: python3 list.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add geosite.txt @cn.txt cn.txt !cn.txt ads.txt @ads.txt category.txt ./-.txt
          git commit -m "Update file"
          git push
